flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- esqueleto-2.5.3
- aeson-1.2.1.0
- base-orphans-0.6
- jose-0.6.0.2
- mmorph-1.1.0
- persistent-2.7.0
- primitive-0.6.2.0
- semigroupoids-5.2
- vector-0.12.0.1
- wai-extra-3.0.20.0
resolver: lts-8.17
